# Generated by Django 4.2.22 on 2025-06-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="verification_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
