FROM node:18-alpine

# Use existing node user for security
USER node

WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
EXPOSE 3000
CMD ["npm", "start", "--", "--port", "3000"]
