repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
    - id: black
      language_version: python3.9
      args: [--line-length=88]

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.280
  hooks:
    - id: ruff
      args: [--fix]

- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.45.0
  hooks:
    - id: eslint
      additional_dependencies:
        - eslint@8.45.0
        - eslint-plugin-react@7.32.2
      files: frontend/src/.*\.(js|jsx|ts|tsx)$
