
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ventai
      POSTGRES_PASSWORD: ventai123
      POSTGRES_DB: ventai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: /Users/olegkizyma/workspaces/MVP/ventai-app/backend
    image: ventai-backend:latest
    container_name: ventai-backend
    env_file:
      - .env
      - .env.development
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
    ports:
      - "8000:8000"
    command: ["./venv/bin/python", "src/fastapi_app/main.py"]
    depends_on:
      - postgres
      - redis
    networks:
      - ventai-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ventai-frontend:latest
    container_name: ventai-frontend
    env_file:
      - .env
      - .env.development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    command: ["npm", "start"]
    depends_on:
      - backend
    networks:
      - ventai-network

volumes:
  postgres_data:
  redis_data:

networks:
  ventai-network:
    driver: bridge
