import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { useRef } from 'react';
import { Group } from 'three';

// Auto-generated by: https://github.com/pmndrs/gltfjsx
export default function BuildingModel(props: any) {
  const group = useRef<Group>(null!);
  
  // Load building model
  const { nodes, materials } = useGLTF('/models/building.glb');
  
  // Rotate model slowly
  useFrame(() => {
    if (group.current) {
      group.current.rotation.y += 0.002;
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh 
        geometry={nodes.building.geometry} 
        material={materials.concrete} 
        position={[0, -1, 0]}
      />
      <mesh
        geometry={nodes.windows.geometry}
        material={materials.glass}
      />
      <mesh
        geometry={nodes.hvac.geometry}
        material={materials.metal}
      />
    </group>
  );
}

useGLTF.preload('/models/building.glb');
