version: "3"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ventai-postgres-dev
    restart: unless-stopped
    env_file:
      - .env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ventai-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: ventai-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    env_file:
      - .env.db
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ventai-network

volumes:
  postgres_data:
    name: ventai_postgres_data_dev
  redis_data:
    name: ventai_redis_data_dev

networks:
  ventai-network:
    name: ventai-network-dev
    driver: bridge
