# Generated by Django 5.2.2 on 2025-06-08 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("analysis_complete", "Analysis Complete"),
                            ("new_data", "New Data Available"),
                            ("time_based", "Time Based"),
                        ],
                        max_length=50,
                    ),
                ),
                ("trigger_config", models.JSONField(default=dict)),
                ("condition", models.TextField(blank=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create_task", "Create Task"),
                            ("send_notification", "Send Notification"),
                            ("run_script", "Run Script"),
                        ],
                        max_length=50,
                    ),
                ),
                ("action_config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
