# Generated by Django 5.2.2 on 2025-06-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_userprofile_verification_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dashboard_preferences",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
