'''Enhance Financial Models

Revision ID: 2025_06_11
Revises: 2025_06_10_add_performance_indexes
Create Date: 2025-06-11 00:00:00.000000
'''
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2025_06_11'
down_revision = '2025_06_10_add_performance_indexes'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_forecasts', sa.Column('forecast_type', sa.String(), nullable=False, server_default='baseline'))
    op.create_index('idx_financial_forecast_date', 'financial_forecasts', ['forecast_date'], unique=False)
    op.create_index('idx_financial_forecast_period', 'financial_forecasts', ['period'], unique=False)
    op.create_index('idx_financial_forecast_project_date', 'financial_forecasts', ['project_id', 'forecast_date'], unique=False)
    
    op.add_column('financial_projects', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('financial_projects', sa.Column('region', sa.String(), nullable=True))
    op.add_column('financial_projects', sa.Column('industry', sa.String(), nullable=True))
    op.create_index('idx_financial_project_dates', 'financial_projects', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_financial_project_region_industry', 'financial_projects', ['region', 'industry'], unique=False)
    op.create_index('idx_financial_project_status', 'financial_projects', ['status'], unique=False)
    
    op.add_column('financial_transactions', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('financial_transactions', sa.Column('cost_center', sa.String(), nullable=True))
    op.create_index('idx_financial_transaction_category', 'financial_transactions', ['category'], unique=False)
    op.create_index('idx_financial_transaction_date', 'financial_transactions', ['date'], unique=False)
    op.create_index('idx_financial_transaction_project_date', 'financial_transactions', ['project_id', 'date'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_financial_transaction_project_date', table_name='financial_transactions')
    op.drop_index('idx_financial_transaction_date', table_name='financial_transactions')
    op.drop_index('idx_financial_transaction_category', table_name='financial_transactions')
    op.drop_column('financial_transactions', 'cost_center')
    op.drop_column('financial_transactions', 'payment_method')
    
    op.drop_index('idx_financial_project_status', table_name='financial_projects')
    op.drop_index('idx_financial_project_region_industry', table_name='financial_projects')
    op.drop_index('idx_financial_project_dates', table_name='financial_projects')
    op.drop_column('financial_projects', 'industry')
    op.drop_column('financial_projects', 'region')
    op.drop_column('financial_projects', 'client_id')
    
    op.drop_index('idx_financial_forecast_project_date', table_name='financial_forecasts')
    op.drop_index('idx_financial_forecast_period', table_name='financial_forecasts')
    op.drop_index('idx_financial_forecast_date', table_name='financial_forecasts')
    op.drop_column('financial_forecasts', 'forecast_type')
    # ### end Alembic commands ###
