name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r backend/requirements.txt
      - run: python backend/manage.py test
      - name: Run flake8
        run: |
          pip install flake8
          flake8 backend/

  lint-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: cd frontend && npm install
      - run: cd frontend && npm test
      - name: Run ESLint
        run: cd frontend && npx eslint src/

  deploy:
    needs: [lint-test-backend, lint-test-frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to production
        run: |
          echo "Додайте тут команди для деплою"
          # Наприклад:
          # ssh user@server "cd /path/to/app && git pull && docker-compose up -d --build"
