name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  frontend-build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Install Frontend Dependencies
      run: npm ci
      working-directory: ./frontend
    - name: Build Frontend
      run: npm run build
      working-directory: ./frontend
    - name: Test Frontend
      run: npm test
      working-directory: ./frontend

  backend-build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: backend/requirements.txt
    - name: Install Backend Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./backend
    - name: Test Backend
      run: pytest
      working-directory: ./backend

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js for ESLint
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Install Frontend Lint Dependencies
      run: npm ci
      working-directory: ./frontend
    - name: Run ESLint
      run: npm run lint
      working-directory: ./frontend
    - name: Set up Python for Pylint
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: backend/requirements.txt
    - name: Install Backend Lint Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
      working-directory: ./backend
    - name: Run Pylint
      run: pylint **/*.py
      working-directory: ./backend
